//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTP
    {
        public int IdBtp { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> nbrannee { get; set; }
        public Nullable<int> Homolgue { get; set; }
        public Nullable<int> IdNiveau { get; set; }
    }
}
