//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BultainGenral
    {
        public int Idetudiant { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<double> Note2 { get; set; }
        public Nullable<double> Note3 { get; set; }
        public int IdNote { get; set; }
        public double Note1 { get; set; }
        public int IdCour { get; set; }
        public string Libelle { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> nbdabsence { get; set; }
    }
}
