//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploie
    {
        public int IdEmploie { get; set; }
        public string NomEmploie { get; set; }
        public int IdCalendrier { get; set; }
        public int IdSalle { get; set; }
        public int IdCour { get; set; }
    }
}
