//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Entites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ICFIPEntities : DbContext
    {
    
    
     public ICFIPEntities(string Strconnection)
            : base(Strconnection)
        {
    	}
        public ICFIPEntities()
            : base("name=ICFIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateur { get; set; }
        public virtual DbSet<BTP> BTP { get; set; }
        public virtual DbSet<BTS> BTS { get; set; }
        public virtual DbSet<Calendrier> Calendrier { get; set; }
        public virtual DbSet<CAP> CAP { get; set; }
        public virtual DbSet<Cour> Cour { get; set; }
        public virtual DbSet<Emploie> Emploie { get; set; }
        public virtual DbSet<Enseignant> Enseignant { get; set; }
        public virtual DbSet<Etudiant> Etudiant { get; set; }
        public virtual DbSet<Formation> Formation { get; set; }
        public virtual DbSet<mois> mois { get; set; }
        public virtual DbSet<Niveau> Niveau { get; set; }
        public virtual DbSet<NiveauFormation> NiveauFormation { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Presence> Presence { get; set; }
        public virtual DbSet<PresenceEnse> PresenceEnse { get; set; }
        public virtual DbSet<Salle> Salle { get; set; }
        public virtual DbSet<Semestre> Semestre { get; set; }
        public virtual DbSet<Sendmail> Sendmail { get; set; }
        public virtual DbSet<Specialite> Specialite { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tab_BTP> Tab_BTP { get; set; }
        public virtual DbSet<Tab_BTS> Tab_BTS { get; set; }
        public virtual DbSet<Tab_CAP> Tab_CAP { get; set; }
        public virtual DbSet<TypeSexe> TypeSexe { get; set; }
        public virtual DbSet<TypeSpecialite> TypeSpecialite { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual DbSet<BultainGenral> BultainGenral { get; set; }
        public virtual DbSet<VtPEnsig> VtPEnsig { get; set; }
        public virtual DbSet<VueAbsence> VueAbsence { get; set; }
        public virtual DbSet<VueBultain> VueBultain { get; set; }
        public virtual DbSet<VueFormationNiveau> VueFormationNiveau { get; set; }
        public virtual DbSet<VueNote> VueNote { get; set; }
        public virtual DbSet<VTotalAbsence> VTotalAbsence { get; set; }
        public virtual DbSet<calendr> calendr { get; set; }
    
        public virtual ObjectResult<GetBultainResult> GetBultain()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBultainResult>("GetBultain");
        }
    }
}
