//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_BTS
    {
        public int IdTabBts { get; set; }
        public int IdAdministrateur { get; set; }
        public int IdCour { get; set; }
        public int IdBts { get; set; }
    }
}
