//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class VueAbsence
    {
        public int Idetudiant { get; set; }
        public Nullable<int> NbAbsence { get; set; }
        public int IdCour { get; set; }
        public string LibelleCour { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> IdSemestre { get; set; }
        public string Observation { get; set; }
    }
}
