//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendrier
    {
        public int IdCalendrier { get; set; }
        public Nullable<int> Anne { get; set; }
        public Nullable<int> Mois { get; set; }
        public Nullable<int> Jour { get; set; }
        public Nullable<int> Heur { get; set; }
        public Nullable<int> Minute { get; set; }
        public Nullable<int> Seconde { get; set; }
    }
}
