//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int Idetudiant { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> DateNiassance { get; set; }
        public string Sexe { get; set; }
        public Nullable<int> IdNiveau { get; set; }
        public Nullable<int> Tel { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IdBts { get; set; }
        public Nullable<int> IdCour { get; set; }
        public string Matricule { get; set; }
        public string LieDeNaissene { get; set; }
        public string NCin { get; set; }
        public Nullable<int> IdFormation { get; set; }
        public Nullable<int> IdSpetialite { get; set; }
        public Nullable<int> nbinscription { get; set; }
        public string MotdePasse { get; set; }
    }
}
