//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Data
{
    using System;
    
    public partial class GetBultainResult
    {
        public Nullable<int> IdCour { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> IdNote { get; set; }
        public Nullable<double> Note1 { get; set; }
        public Nullable<int> Idetudiant { get; set; }
        public Nullable<double> Note2 { get; set; }
        public Nullable<double> Note3 { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
    }
}
