//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiveauFormation
    {
        public int IdNiveauFormation { get; set; }
        public Nullable<int> IdNiveau { get; set; }
        public Nullable<int> IdFormation { get; set; }
    }
}
