//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICFIP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int IdAbsence { get; set; }
        public Nullable<int> IdCour { get; set; }
        public Nullable<int> Idetudiant { get; set; }
        public Nullable<int> Absence { get; set; }
        public Nullable<System.DateTime> DateAbsnece { get; set; }
        public Nullable<System.TimeSpan> HeurAbsence { get; set; }
        public Nullable<int> IdBts { get; set; }
        public Nullable<int> IdBtp { get; set; }
        public Nullable<int> IdCap { get; set; }
        public Nullable<int> IdNiveau { get; set; }
        public Nullable<int> IdSemestre { get; set; }
        public Nullable<int> IdFormation { get; set; }
        public Nullable<int> nbdabsence { get; set; }
        public Nullable<int> IdSpetialite { get; set; }
    }
}
